services:
    apache:
        image: tugboatqa/httpd
        aliases: test
        http: true
        https: false
        commands:
            init:
                - echo "********** INIT **********"
                - apt-get update
                - apt-get install bsd-mailx
                - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
                - echo "alias ll='ls -la'" >> /root/.bashrc
                - echo "export PATH=$PATH:${TUGBOAT_ROOT}" >> /root/.bashrc
                - echo "#!/bin/sh" > "${TUGBOAT_ROOT}/hello-world"
                - echo "echo 'hello world'" >> "${TUGBOAT_ROOT}/hello-world"
                - chmod +x hello-world
            update:
                - echo "********** UPDATE **********"
            build:
                - echo "********** BUILD **********"
                - cat .tugboat/tugboat.txt | mail -s "[1] Tugboat Preview ${TUGBOAT_PREVIEW_ID}" tugboat@example.com
                - cat .tugboat/tugboat.txt | mail -s "[2] Tugboat Preview ${TUGBOAT_PREVIEW_ID}" tugboat@example.com
                - cat .tugboat/tugboat.txt
