services:
  nginx:
    image: tugboatqa/nginx
    default: true
    expose: 80
    subpath: true
    commands:
      init:
        - ln -snf "${TUGBOAT_ROOT}/revproxy/" "${DOCROOT}"
      build:
        - bash $TUGBOAT_ROOT/.tugboat/scripts/nginx/build.sh
