services:
    default:
        image: tugboatqa/httpd
        default: true
        http: true
        https: false
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"

    apache:
        image: tugboatqa/httpd
        expose: 80

    nginx:
        image: tugboatqa/nginx
