services:
  server:
    image: tugboatqa/debian
    default: true
    expose: 3000
    subpath: true
    commands:
      init:
        - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        - apt install -y nodejs
      build:
        - bash $TUGBOAT_ROOT/.tugboat/scripts/build.sh
      start:
        - cd $TUGBOAT_ROOT/server/ && npm start  &
