services:
    default:
        image: tugboatqa/httpd
        default: true
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"

    apache:
        image: tugboatqa/httpd

    nginx:
        image: tugboatqa/nginx
